apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cicd
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: test-cicd
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
